# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: "3.4"

services:
  catalogdb:
    container_name: catalogdb
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  basketdb:
    container_name: basketdb
    ports:
      - 6379:6379

  catalogapi:
    container_name: catalogapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8000:5000
    depends_on:
      - catalogdb
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  basketapi:
    container_name: basketapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8001:5001
    depends_on:
      - basketdb
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
